services:
  php:
    image: php:8.3-fpm
    build: ..
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - "54511:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: docker-playground
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
